namespace WINIT.Models;

public record IncomingCustomer
(
    string customerCode,
    string customerName,
    string contactNo,
    string email,
    string cityCode,
    string cityName,
    string regionCode,
    string regionName,
    bool isActive,
    bool isBlocked,
    decimal creditLimit,
    int creditDays,
    string arabicDescription,
    string parentCustomerCode,
    string parentCustomerName,
    string fax,
    string address1,
    string address2,
    string address3,
    string address4,
    string longitude,
    string latitude,
    string contactPersonName,
    string cityNameArabic,
    string priceListCode,
    string customerGroupCode,
    string customerGroupName,
    string paymentTermName,
    string paymentTermCode,
    string customerType,
    string channelCode,
    string channelName,
    string subChannelCode,
    string subChannelName
);
